name: Update gameVersion

on:
  issues:
    types: [labeled]

jobs:
  process_issue:
    # Runs ONLY if the newly added label is 'approved' AND it's the correct issue template
    if: >
      github.event.label.name == 'gameVersion Update' &&
      contains(github.event.issue.labels.*.name, 'list-input')
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Parse Issue to JSON
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          .\.github\scripts\parse_issue.ps1 -IssueBody $env:ISSUE_BODY
